# Generated by Django 4.2.11 on 2024-04-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, unique=True)),
                ('born_date', models.CharField(max_length=30)),
                ('born_location', models.CharField(max_length=80)),
                ('description', models.CharField()),
            ],
        ),
    ]
